#Convert list of dictionaries to Dataframe

In [ ]:
import pandas as pd
d = [{'city':'Delhi',"data":1000}, {'city':'Bangalore',"data":2000},{'city':'Mumbai',"data":1000}]
d

[{'city': 'Delhi', 'data': 1000},
 {'city': 'Bangalore', 'data': 2000},
 {'city': 'Mumbai', 'data': 1000}]

In [ ]:
# Convert the list of dictionaries 'd' into a dataframe.
df = pd.DataFrame(d)
df

        city  data
0      Delhi  1000
1  Bangalore  2000
2     Mumbai  1000

#Convert CSV files to Dataframe

In [ ]:
# Download worldcities csv file
!wget "https://raw.githubusercontent.com/dipanjanS/practical-machine-learning-with-python/master/notebooks/Ch02_The_Python_ML_Ecosystem/simplemaps-worldcities-basic.csv" -O simplemaps-worldcities-basic.csv 

# Read in csv file and convert it to dataframe
city_data = pd.read_csv(filepath_or_buffer='simplemaps-worldcities-basic.csv')

# Show the first 10 rows of converted dataframe
city_data.head(n=10)

--2022-05-03 17:29:34--  https://raw.githubusercontent.com/dipanjanS/practical-machine-learning-with-python/master/notebooks/Ch02_The_Python_ML_Ecosystem/simplemaps-worldcities-basic.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 562804 (550K) [text/plain]
Saving to: ‘simplemaps-worldcities-basic.csv’

simplemaps-worldcit 100%[===================>] 549.61K  --.-KB/s    in 0.04s

2022-05-03 17:29:34 (12.8 MB/s) - ‘simplemaps-worldcities-basic.csv’ saved [562804/562804]

,city,city_ascii,lat,lng,pop,country,iso2,iso3,province
0,Qal eh-ye Now,Qal eh-ye,34.983000,63.133300,2997.0,Afghanistan,AF,AFG,Badghis
1,Chaghcharan,Chaghcharan,34.516701,65.250001,15000.0,Afghanistan,AF,AFG,Ghor
2,Lashkar Gah,Lashkar Gah,31.582998,64.360000,201546.0,Afghanistan,AF,AFG,Hilmand
3,Zaranj,Zaranj,31.112001,61.886998,49851.0,Afghanistan,AF,AFG,Nimroz
4,Tarin Kowt,Tarin Kowt,32.633298,65.866699,10000.0,Afghanistan,AF,AFG,Uruzgan
5,Zareh Sharan,Zareh Sharan,32.850000,68.416705,13737.0,Afghanistan,AF,AFG,Paktika
6,Asadabad,Asadabad,34.866000,71.150005,48400.0,Afghanistan,AF,AFG,Kunar
7,Taloqan,Taloqan,36.729999,69.540004,64256.0,Afghanistan,AF,AFG,Takhar
8,Mahmud-E Eraqi,Mahmud-E Eraqi,35.016696,69.333301,7407.0,Afghanistan,AF,AFG,Kapisa
9,Mehtar Lam,Mehtar Lam,34.650000,70.166701,17345.0,Afghanistan,AF,AFG,Laghman

#Data Access

##Head and Tail

Get the last 10 rows of **city_data**:

In [ ]:
city_data.tail(10)

,city,city_ascii,lat,lng,pop,country,iso2,iso3,province
7312,Karoi,Karoi,-16.819556,29.679987,13194.0,Zimbabwe,ZW,ZWE,Mashonaland West
7313,Chinhoyi,Chinhoyi,-17.359626,30.180008,52812.0,Zimbabwe,ZW,ZWE,Mashonaland West
7314,Kariba,Kariba,-16.529600,28.800040,23133.5,Zimbabwe,ZW,ZWE,Mashonaland West
7315,Hwange,Hwange,-18.370004,26.500026,33599.5,Zimbabwe,ZW,ZWE,Matabeleland North
7316,Gweru,Gweru,-19.450041,29.820030,164715.5,Zimbabwe,ZW,ZWE,Midlands
7317,Mutare,Mutare,-18.970019,32.650038,216785.0,Zimbabwe,ZW,ZWE,Manicaland
7318,Kadoma,Kadoma,-18.330006,29.909947,56400.0,Zimbabwe,ZW,ZWE,Mashonaland West
7319,Chitungwiza,Chitungwiza,-18.000001,31.100003,331071.0,Zimbabwe,ZW,ZWE,Harare
7320,Harare,Harare,-17.817790,31.044709,1557406.5,Zimbabwe,ZW,ZWE,Harare
7321,Bulawayo,Bulawayo,-20.169998,28.580002,697096.0,Zimbabwe,ZW,ZWE,Bulawayo

##Slicing and Dicing

In [ ]:
series_es = city_data.lat
type(series_es)

pandas.core.series.Series

Get the first 5 odd number of rows of **series_es**:

In [ ]:
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

Get the first 8 rows of **series_es**:

In [ ]:
series_es[:8]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
7    36.729999
Name: lat, dtype: float64

Get first 8 rows of **city_data**:

In [ ]:
city_data[:8]

,city,city_ascii,lat,lng,pop,country,iso2,iso3,province
0,Qal eh-ye Now,Qal eh-ye,34.983000,63.133300,2997.0,Afghanistan,AF,AFG,Badghis
1,Chaghcharan,Chaghcharan,34.516701,65.250001,15000.0,Afghanistan,AF,AFG,Ghor
2,Lashkar Gah,Lashkar Gah,31.582998,64.360000,201546.0,Afghanistan,AF,AFG,Hilmand
3,Zaranj,Zaranj,31.112001,61.886998,49851.0,Afghanistan,AF,AFG,Nimroz
4,Tarin Kowt,Tarin Kowt,32.633298,65.866699,10000.0,Afghanistan,AF,AFG,Uruzgan
5,Zareh Sharan,Zareh Sharan,32.850000,68.416705,13737.0,Afghanistan,AF,AFG,Paktika
6,Asadabad,Asadabad,34.866000,71.150005,48400.0,Afghanistan,AF,AFG,Kunar
7,Taloqan,Taloqan,36.729999,69.540004,64256.0,Afghanistan,AF,AFG,Takhar

Get the first 4 columns of the first 5 rows of **city_data**:

In [ ]:
city_data.iloc[:5, :4]

            city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

Select cities that have population of more than 10
million and select columns with column name start with the letter p:

In [ ]:
city_data[city_data['pop'] > 10000000][city_data.columns[pd.Series(city_data.columns).str.startswith('p')]]

             pop                province
360   11862073.0  Ciudad de Buenos Aires
1171  14433147.5               São Paulo
2068  14797756.0                Shanghai
3098  11779606.5                   Delhi
3110  15834918.0             Maharashtra
3492  22006299.5                   Tokyo
4074  14919501.0        Distrito Federal
4513  11877109.5                    Sind
5394  10452000.0                  Moskva
6124  10003305.0                Istanbul
7071  13524139.0                New York

#Data Operations

##Missing data and the fillna function

In [ ]:
import numpy as np
df = pd.DataFrame(np.random.randn(8, 3), columns=['A', 'B', 'C'])
df.iloc[4,2] = np.nan
df

          A         B         C
0  1.430375  0.466910 -0.861559
1  1.598080 -0.435553 -1.307238
2 -1.346255 -1.448025  0.332528
3 -1.807295 -1.043334 -0.438036
4  2.265326 -2.155619       NaN
5  1.037437  0.928820 -0.012085
6  0.733038  1.116609 -1.055005
7  1.307170  0.146897  1.696635

Replace all the "NaN" in **df** with "0":

In [ ]:
df.fillna(0)

          A         B         C
0  1.430375  0.466910 -0.861559
1  1.598080 -0.435553 -1.307238
2 -1.346255 -1.448025  0.332528
3 -1.807295 -1.043334 -0.438036
4  2.265326 -2.155619  0.000000
5  1.037437  0.928820 -0.012085
6  0.733038  1.116609 -1.055005
7  1.307170  0.146897  1.696635

#Descriptive Statistics functions

In [ ]:
columns_numeric = ['lat','lng','pop']

Get average 'lat', 'lng', and 'pop' values:

In [ ]:
city_data[columns_numeric].mean()

lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64

Get sum of 'lat', 'lng', and 'pop' values:

In [ ]:
city_data[columns_numeric].sum()

lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64

Get total number of 'lat', 'lng', and 'pop' values:

In [ ]:
city_data[columns_numeric].count()

lat    7322
lng    7322
pop    7322
dtype: int64

Get 75 percentile of 'lat', 'lng', and 'pop' values:

In [ ]:
city_data[columns_numeric].quantile(0.75)

lat        43.575448
lng        73.103628
pop    200172.625000
Name: 0.75, dtype: float64

Get sums of each row:

In [ ]:
city_data[columns_numeric].sum(axis = 1)

0       3.095116e+03
1       1.509977e+04
2       2.016419e+05
3       4.994400e+04
4       1.009850e+04
            ...
7317    2.167987e+05
7318    5.641158e+04
7319    3.310841e+05
7320    1.557420e+06
7321    6.971044e+05
Length: 7322, dtype: float64

Calculate
the most important statistics for numerical data in one go so that we don’t have to use individual functions:

In [ ]:
city_data[columns_numeric].describe()

               lat          lng           pop
count  7322.000000  7322.000000  7.322000e+03
mean     20.662876    10.711914  2.654631e+05
std      29.134818    79.044615  8.287622e+05
min     -89.982894  -179.589979 -9.900000e+01
25%      -0.324710   -64.788472  1.734425e+04
50%      26.792730    18.617509  6.132275e+04
75%      43.575448    73.103628  2.001726e+05
max      82.483323   179.383304  2.200630e+07